### ISSUE TITLE
How to auth with userToken instead of apiKey and apiToken?

### ISSUE THREAD

**Issue by Mura75** [voiceittech/VoiceItApi2AndroidSDK#3]
Hi, thanks you for this library!
I can make requests with apiKey and apiToken, but with userToken request doesn't work. I want to use userToken for security and don't want to store apiKey and apiToken in app because they can be extracted.

**Comment by StephenAkers** [comment]
Thanks for noticing this!
This issue is not related to this repo and has been resolved. It should work now.
If you have any further issues with this, please email support@voiceit.io
