### ISSUE TITLE
No support to get users of a specific group

### ISSUE THREAD

**Issue by kmvkrish** [voiceittech/VoiceItApi2AndroidSDK#4]
In the VoiceItAPI2AndroidSDK, there is support to get all the groups a particular user is linked to. We can get this using [https://api.voiceit.io/?java#get-groups-for-user](https://api.voiceit.io/?java#get-groups-for-user). But there is no support for getting all the users of a specific group.
This would be very helpful to get all the users of a group, map then to the local users details in the app and proceed with verification. Without this, there will be huge logic execution to map all the users of the VoiceIt account, and mapping them to the DB.

**Comment by StephenAkers** [comment]
Hi kmvkrish,

You can use the getGroup(String groupId, AsyncHttpResponseHandler responseHandler) method to get all of the users in the group
